sudo: required
services: 
  - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # NEED TO ADD THE TRAVIS ENCRYPTED FILE FOR THE SERVICE ACNT LOGIN
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-398106
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-cluster  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build-t kalvete/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run -e CI=true kalvete/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master